when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
register:
    path: /register
    controller: App\Controller\RegistrationController::register