controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# Si on veux declarer une nouvelle route  pour navigeur entre les controlleurs
dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index